# Generated by Django 2.1.2 on 2018-10-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('nom', models.TextField(max_length=50)),
                ('prénom', models.TextField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=50)),
            ],
        ),
    ]
