# Generated by Django 2.1.1 on 2018-10-14 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HoneyPot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(blank=True, max_length=20)),
                ('password', models.TextField(blank=True, max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Formulaire de Login',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, max_length=20)),
                ('prenom', models.TextField(blank=True, max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True, max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Formulaire de Contact',
            },
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
