# Generated by Django 2.1.2 on 2018-10-13 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HoneyPot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=50)),
                ('prénom', models.TextField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=50)),
                ('ip', models.TextField(max_length=50)),
                ('user_agent', models.TextField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='message',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='nom',
            new_name='user_agent',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='prénom',
        ),
        migrations.AddField(
            model_name='profil',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
