# Generated by Django 2.1.2 on 2018-10-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoneyPot', '0003_auto_20181013_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['date'], 'verbose_name': 'Formulaire de Contact'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'ordering': ['date'], 'verbose_name': 'Formulaire de Login'},
        ),
    ]
