# Generated by Django 2.1.2 on 2018-10-13 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HoneyPot', '0004_auto_20181013_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ip',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prénom',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_agent',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profil',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ip',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profil',
            name='login',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profil',
            name='password',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user_agent',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
