# Generated by Django 2.1.2 on 2018-10-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoneyPot', '0005_auto_20181013_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='Connex',
        ),
    ]
