# Generated by Django 2.1.2 on 2018-10-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoneyPot', '0007_auto_20181013_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prénom',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
