# Generated by Django 2.1.2 on 2018-10-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoneyPot', '0008_auto_20181013_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connex',
            options={'verbose_name': 'Formulaire de Login'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Formulaire de Contact'},
        ),
    ]
