# Generated by Django 2.1.2 on 2018-10-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoneyPot', '0009_auto_20181013_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='prénom',
            new_name='prenom',
        ),
        migrations.AlterField(
            model_name='connex',
            name='login',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='connex',
            name='password',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
