# Generated by Django 2.1.2 on 2018-10-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoneyPot', '0010_auto_20181014_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connex',
            name='login',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='connex',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prenom',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
